#!/bin/bash
set -e
COMMAND_BASENAME=`basename $0`
CM_WORKINGDIR=/Users/djegan/dev/cm/cm

USAGE="axupg <destination machine> [tree-ish]
    If no parameters are given then the current HEAD is used
    if one parameter is given then that tree-ish (commit, tag or tree) is used"

# Export source code to temp directory
if [ $# -eq 1 ]
then
    DEST_MACHINE=$1
    pushd $CM_WORKINGDIR
    ABBR_HASH=`git show -s --format="%h" HEAD^0`
    TMP_WORKINGDIR=`mktemp -d "/tmp/HEAD-${ABBR_HASH}.${COMMAND_BASENAME}.tmpXXXXXXXXXX"` || exit 1
    git archive HEAD | tar x -C $TMP_WORKINGDIR
    popd
elif [ $# -eq 2 ]
then
    DEST_MACHINE=$1
    pushd $CM_WORKINGDIR
    HASH=`git show -s --format="%H" $2^0`
    ABBR_HASH=`git show -s --format="%h" $2^0`
    MESSAGE=`git show -s --format="%f" $2^0`
    if [ "$2" = "$HASH" ]
    then
        ARCHIVE_TITLE=`echo $MESSAGE|sed 's,/,-,g'`
    else
        ARCHIVE_TITLE=`echo ${2}|sed 's,/,-,g'`
    fi
    TMP_WORKINGDIR=`mktemp "/tmp/${ARCHIVE_TITLE}-${ABBR_HASH}.${COMMAND_BASENAME}.tmpXXXXXXXXXX"` || exit 1
    git archive "$2" | tar x -C $TMP_WORKINGDIR
    popd
else
    echo
    echo "   Usage: $USAGE"
    echo
    exit 1
fi

# Build release
pushd $TMP_WORKINGDIR
mvn clean package -Denforcer.skip=true -Dmaven.test.skip=true
AX_VERSION=`ls cm-core/target/cm-core-*-CmCommandLine.jar | sed 's,cm-core/target/cm-core-,,' | sed 's,-CmCommandLine.jar,,'`
popd

# Copy to remote machine
scp  -i ~/.ssh/ApxiumSandbox.pem $TMP_WORKINGDIR/cm-core/target/cm-core-"$AX_VERSION"-CmCommandLine.jar admin@"$DEST_MACHINE".apxium.com:./releases/
scp  -i ~/.ssh/ApxiumSandbox.pem $TMP_WORKINGDIR/cm-server/target/cm-server-"$AX_VERSION".jar admin@"$DEST_MACHINE".apxium.com:./releases/

# Link on remote machine and restart server
ssh -i ~/.ssh/ApxiumSandbox.pem admin@"$DEST_MACHINE".apxium.com "ln -sf ~/releases/cm-server-"$AX_VERSION".jar ~/bin/cm-server.jar"
ssh -i ~/.ssh/ApxiumSandbox.pem admin@"$DEST_MACHINE".apxium.com "ln -sf ~/releases/cm-core-"$AX_VERSION"-CmCommandLine.jar ~/bin/CmCommandLine.jar"
ssh -i ~/.ssh/ApxiumSandbox.pem admin@"$DEST_MACHINE".apxium.com "stopob"
ssh -i ~/.ssh/ApxiumSandbox.pem admin@"$DEST_MACHINE".apxium.com "ob upgradedb"
ssh -i ~/.ssh/ApxiumSandbox.pem admin@"$DEST_MACHINE".apxium.com "startob"
