#!/bin/bash

source gitlib.sh

verifyNoUncommittedChanges
verifyNoUnpushedCommits

# Get the version to branch from
RELEASE_VERSION=`printMostRecentVersion`
while true; do
    echo
    if [ "$RELEASE_VERSION" != "" ]
    then
        read -p "   Release version to branch from [$RELEASE_VERSION] ? " value
    else
        read -p "   Release version to branch from ? " value
    fi
    if [ "$value" != "" ]
    then
        filteredValue=`filterOutInvalidVersions "$value"`
        if [ "$filteredValue" = "" ]
        then
            echo "   \"$value\" is an invalid version, please re-enter"
        else
            RELEASE_VERSION="$filteredValue"
            break
        fi
    else
        if [ "$RELEASE_VERSION" = "" ]
        then
            echo "   Please enter the release version to branch from"
        else
            break
        fi
    fi
done

printMostRecentBranchVersionFor $RELEASE_VERSION
LAST_BRANCH_VERSION=`printMostRecentBranchVersionFor $RELEASE_VERSION`
echo "LAST_BRANCH_VERSION = \"$LAST_BRANCH_VERSION\""

#printMostRecentBranchVersionFor $RELEASE_VERSION
printNextBranchVersionFor $RELEASE_VERSION
NEXT_BRANCH_VERSION=`printNextBranchVersionFor $RELEASE_VERSION`
echo "NEXT_BRANCH_VERSION = \"$NEXT_BRANCH_VERSION\""

# Get the branch name
BRANCH_NAME=""
while true; do
    echo
    if [ "$BRANCH_NAME" != "" ]
    then
        read -p "   New branch name [$BRANCH_NAME] ? " value
    else
        read -p "   New branch name ? " value
    fi
    if [ "$value" != "" ]
    then
        BRANCH_NAME="$value"
        break
    else
        echo "   Please enter the new branch name"
    fi
done

checkout "v$RELEASE_VERSION"
checkoutOnANewBranch "$BRANCH_NAME"
updatePomfileVersions "$NEXT_BRANCH_VERSION"-SNAPSHOT
addAllModificationsAndCommitWithMessage "Updating poms for ""$NEXT_BRANCH_VERSION""-SNAPSHOT development"
echo