#!/bin/bash

source gitlib.sh

verifyNoUncommittedChanges
verifyNoUnpushedCommits
verifyPomFileHasASnapshotVersion

# Extract release version etc
ORIG_BRANCH=`git branch| grep '^\* '|sed 's/\* //'`
RELEASE_VERSION=`mvn blah|egrep '^\[INFO\] Building .+ [0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$'|sed 's/\[INFO\] Building .* //'|sed 's/-SNAPSHOT$//'`
MINOR_RELEASE=`echo $RELEASE_VERSION|sed 's/.*\.//'`
NEXT_SNAPSHOT_VERSION=`echo $RELEASE_VERSION|sed 's/[^.]*$//'`$(($MINOR_RELEASE + 1))-SNAPSHOT
TEMP_BRANCH="v$RELEASE_VERSION""_tmpBranch"

confimBeforeProceeding "   Do you wish to release v$RELEASE_VERSION (y/n) ?"

# Checkout a temp branch to perform work on
if ! git checkout -b $TEMP_BRANCH
then
    exit 1
fi

# Update POM file versions
if ! mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$RELEASE_VERSION
then
    exit 1
fi

# Add and commit changed POM file versions (but do not push)
if ! git add -A
then
    exit 1
fi
if ! git commit -m "v"$RELEASE_VERSION
then
    exit 1
fi


echo "ORIG_BRANCH: $ORIG_BRANCH"
echo "RELEASE_VERSION: $RELEASE_VERSION"
echo "MINOR_RELEASE: $MINOR_RELEASE"
echo "NEXT_SNAPSHOT_VERSION: $NEXT_SNAPSHOT_VERSION"
echo "TEMP_BRANCH: $TEMP_BRANCH"
