#!/bin/sh

LATEST_HAL_BU_DAY=`ssh djegan@jack.collectionsmanager.com.au "ls /var/lib/postgresql/backups/hal/cmprd"|tail -1`
LATEST_HAL_MERCHANTDB_BU_DAY=`ssh djegan@jack.collectionsmanager.com.au "ls /var/lib/postgresql/backups/hal/cmmerchantdataprd"|tail -1`
LATEST_MGMCM_BU_DAY=`ssh djegan@mgmcm.com.au "ls /var/lib/postgresql/backups/cmprd"|tail -1`
LATEST_MGMCM_MERCHANTDB_BU_DAY=`ssh djegan@mgmcm.com.au "ls /var/lib/postgresql/backups/cmmerchantdataprd"|tail -1`

LATEST_HAL_BU=`ssh djegan@jack.collectionsmanager.com.au "ls /var/lib/postgresql/backups/hal/cmprd/$LATEST_HAL_BU_DAY"|grep '\.backup$'|tail -1`
LATEST_HAL_MERCHANTDB_BU=`ssh djegan@jack.collectionsmanager.com.au "ls /var/lib/postgresql/backups/hal/cmmerchantdataprd/$LATEST_HAL_MERCHANTDB_BU_DAY"|grep '\.backup$'|tail -1`
LATEST_MGMCM_BU=`ssh djegan@mgmcm.com.au "ls /var/lib/postgresql/backups/cmprd/$LATEST_MGMCM_BU_DAY"|grep '\.backup$'|tail -1`
LATEST_MGMCM_MERCHANTDB_BU=`ssh djegan@mgmcm.com.au "ls /var/lib/postgresql/backups/cmerchantdatamprd/$LATEST_MGMCM_MERCHANTDB_BU_DAY"|grep '\.backup$'|tail -1`

echo
echo "   Latest hal BUs: $LATEST_HAL_BU"
echo "                   $LATEST_HAL_MERCHANTDB_BU"
echo
echo "   Latest mgmcm BUs: $LATEST_MGMCM_BU"
echo "                     $LATEST_MGMCM_MERCHANTDB_BU"
