#!/bin/bash
set -u
set -e
source commonlib.sh
source getbulib.sh

if [ $# -ne 1 ]
then
    echo
    echo "   Usage: refresh <backup-from machine>"
    echo "          e.g. refresh sam"
    echo
    exit 1
fi

if [ "$1" = "fergus" ] || [ "$1" = "ethan" ] || [ "$1" = "karen" ] || [ "$1" = "vlad" ] || [ "$1" = "cal" ]
then
    obd="java -jar "`ls ~/dev/cm/cmAlternate/cm-core/target/cm-core*-SNAPSHOT-CmCommandLine.jar|head -1`""
    mainDb=cmdev
    importDb=cmimportdev
else
    obd="java -jar "`ls ~/dev/cm/cm/cm-core/target/cm-core*-SNAPSHOT-CmCommandLine.jar|head -1`" -c /Users/djegan/etcSBConfig"
    mainDb=cmsbdev
    importDb=cmimportsbdev
fi



echo
echo "    This will completely blow away all data in the main database and the import"
echo "    database as well as deleting everything in the emailArchive and fileStore."
confimBeforeProceeding "    Are you sure you want to do this (y/n) ?"

restoreLatestLocalBackupForServer $1

echo
echo -n ===== Running obd upgradedb
$obd upgradedb

echo
echo ===== Recreating $importDb
psql -h localhost postgres postgres -c "drop database $importDb"
psql -h localhost postgres postgres -c "create database $importDb"

echo
echo -n ===== Running obd createimportdb
$obd createimportdb

echo
echo ===== Flushing fileStore and emailArchive
rm -rf ~/fileStore/*
echo - flushed fileStore
rm -rf ~/emailArchive/*
echo - flushed emailArchive

echo

function  refreshObPayAfterConfirmation {
    echo
    echo "    Would you also like to refresh ObPay data?  This will delete"
    echo "    all data currently in ObPay.  This could be an issues if any other"
    echo "    servers are also configured to use this ObPay server."
    echo "    Note that this will only work for ObPay servers that support"
    echo "    it (e.g. DummyPaymentGateway and obpay-blackhole)"
    while true; do
        read -p "    Are you sure you want to clear out ObPay (y/n) ?" yn
        case $yn in
            [Yy] ) echo;echo  ===== Running obd reset-obpay;$obd reset-obpay;echo - flushed ObPay;break;;
            [Nn] ) echo;break;;
            * ) echo "   Please answer y or n.";;
        esac
    done
}
