#!/bin/sh
set -u
set -e
source remlib.sh

USAGE="dbbackup <databaseName>"

if [ $# -ne 1 ]
then
    echo
    echo "   Usage: $USAGE"
    echo
    exit 1
fi

DBNAME=`getDbNameForServer $1`
SERVER=`getFullyQualifiedNameForServer $1`
BACKUP_FILEPATH=`getBackupFilepathForServer $1 $DBNAME`

backupRemoteDatabase $SERVER $DBNAME $BACKUP_FILEPATH
