#!/bin/bash

echo
echo jack
ssh djegan@jack.collectionsmanager.com.au 'df -h'|grep '^/dev'

echo
echo sam
ssh onebox@sam.apxium.com 'df -h'|grep '^/dev'

echo
echo fergus
ssh onebox@fergus.onebox.net.au 'df -h'|grep '^/dev'

echo
echo vlad
ssh onebox@vlad.onebox.net.au 'df -h'|grep '^/dev'
echo
